// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

// Import the Verifier contract generated by ZoKrates
import "./verifier.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";

contract ScholarPi_PiQ_Token is 
    Initializable, 
    ERC20Upgradeable, 
    OwnableUpgradeable, 
    UUPSUpgradeable 
{
    mapping(string => bool) public hasBeenAssessed;
    Verifier public zkVerifier;

    event MintProofVerified(address indexed researcher, uint256 amount, string evalHash);
    
    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    /**
     * @dev Replaces the constructor for upgradeable proxy deployment.
     * @param _verifierAddress The deployed address of verifier.sol
     * @param initialOwner The address that will hold admin upgrade/mint rights
     */
    function initialize(address _verifierAddress, address initialOwner) public initializer {
        require(_verifierAddress != address(0), "Verifier address cannot be zero");
        require(initialOwner != address(0), "Owner address cannot be zero");

        // Initialize OpenZeppelin base contracts
        __ERC20_init("Pi Quotient", "piQ");
        __Ownable_init(initialOwner);

	// __UUPSUpgradeable_init(); <-- DELETED: No longer needed in OpenZeppelin v5

        zkVerifier = Verifier(_verifierAddress);
    }

    /**
     * @dev Required override for UUPS proxy upgrades, restricted to the owner.
     */
    function _authorizeUpgrade(address newImplementation) internal override onlyOwner {}

    /**
     * @dev Mints piQ to researcher using a true zk-SNARK Groth16 proof.
     */
    function verifyProofAndMint(
        address researcher, 
        uint256 amountWei, 
        string memory evalHash,
        uint256 truncatedHashInt, 
        Verifier.Proof memory proof 
    ) public onlyOwner {
        
        require(!hasBeenAssessed[evalHash], "Fraud Detected: Manuscript already assessed.");
        require(amountWei > 0, "Mint amount must be > 0.");
        require(researcher != address(0), "Cannot mint to the zero address.");

        // 1. Prepare the public input array for the Verifier 
        uint256[1] memory publicInputs = [truncatedHashInt];

        // 2. Execute the native zk-SNARK verification
        bool isValid = zkVerifier.verifyTx(proof, publicInputs);
        require(isValid, "ZK-SNARK Proof Verification Failed! Parameters do not meet the circuit logic.");

        // 3. Mark as assessed to prevent replay attacks
        hasBeenAssessed[evalHash] = true;
        
        // 4. Effect the mint using OpenZeppelin's safe internal _mint function
        _mint(researcher, amountWei);

        emit MintProofVerified(researcher, amountWei, evalHash);
    }

    /**
     * @dev This empty reserved space is put in place to allow future versions to add new
     * variables without shifting down storage in the inheritance chain.
     */
    uint256[50] private __gap;
}