// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./verifier.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * ScholarPi piQ — soulbound contribution token with a state registry.
 *
 * WHY THIS REPLACES THE UPGRADEABLE VERSION
 * -----------------------------------------
 * The previous contract was UUPS-upgradeable. Its constructor called
 * `_disableInitializers()`, which is correct practice for an upgradeable
 * implementation: the implementation is meant to sit behind an ERC1967 proxy,
 * and disabling initializers on the implementation itself stops an attacker
 * from initializing it and taking ownership of the logic contract.
 *
 * That deployment was made WITHOUT a proxy and the application was pointed
 * straight at the implementation. The consequence is not a misconfiguration
 * that can be corrected by calling `initialize()` — it is that `initialize()`
 * reverts unconditionally, forever, by design. The token therefore has no
 * name, no symbol, and an owner of address(0), and every mint reverts.
 *
 * Upgradeability is a real cost paid for a real benefit, and for a
 * single-maintainer research project the benefit was not being collected: the
 * proxy was never deployed, so nothing was ever upgradeable in practice, while
 * the complexity was quietly fatal. This version is a plain, non-upgradeable
 * contract that is fully live the moment the deployment transaction confirms.
 *
 * SOULBOUND
 * ---------
 * The application describes piQ as a soulbound token, but the previous
 * contract inherited an unmodified ERC20 and was freely transferable. That is
 * a substantive mismatch: piQ is meant to record who did assessed work, and a
 * transferable version of that record is a tradeable reputation, which is the
 * opposite of the claim. Transfers are now blocked at the token level, so the
 * documentation and the contract agree.
 *
 * STATE REGISTRY
 * --------------
 * `updateCID`/`getCID` are included here rather than in a second contract.
 * The backend needs somewhere to anchor the IPFS CID of its encrypted state
 * backup, and requiring a separate deployment for two storage slots is what
 * led to the token address being pasted into the registry setting — a valid
 * contract with nowhere to put a CID, so anchoring silently never happened.
 * One address now serves both roles.
 *
 * DEPLOYMENT (Remix, Sepolia)
 * ---------------------------
 *   1. Deploy `verifier.sol` first. Copy its address.
 *   2. Deploy this contract with:
 *        _verifierAddress = the Verifier address from step 1
 *        initialOwner     = 0x6B89DD74DCa5d4DC98599206b1c2dE614066ef40
 *   3. Set PIQ_CONTRACT_ADDRESS and REGISTRY_CONTRACT_ADDRESS to THIS
 *      contract's address. They are deliberately the same value.
 *
 * There is no initialize() step. Everything is set in the constructor, so the
 * contract cannot exist in the half-deployed state the previous one was in.
 *
 * Requires OpenZeppelin Contracts v5.x (non-upgradeable).
 */
contract ScholarPi_PiQ_Token is ERC20, Ownable {
    // ---------------------------------------------------------------------
    // zk-SNARK minting
    // ---------------------------------------------------------------------

    /// Groth16 verifier generated by ZoKrates from circuit.zok.
    Verifier public zkVerifier;

    /// Replay protection: one mint per evaluation hash, ever.
    mapping(string => bool) public hasBeenAssessed;

    // ---------------------------------------------------------------------
    // State registry
    // ---------------------------------------------------------------------

    /// IPFS CID of the most recent encrypted ledger-state backup.
    string private _stateCID;

    /// Block timestamp of the last CID update, so a stale backup is detectable.
    uint256 public cidUpdatedAt;

    event MintProofVerified(address indexed researcher, uint256 amount, string evalHash);
    event VerifierUpdated(address indexed previousVerifier, address indexed newVerifier);
    event StateCIDUpdated(string cid, uint256 timestamp);

    error SoulboundTransferNotAllowed();

    constructor(address _verifierAddress, address initialOwner)
        ERC20("Pi Quotient", "piQ")
        Ownable(initialOwner)
    {
        require(_verifierAddress != address(0), "Verifier address cannot be zero");
        require(initialOwner != address(0), "Owner address cannot be zero");
        zkVerifier = Verifier(_verifierAddress);
    }

    // ---------------------------------------------------------------------
    // Soulbound enforcement
    // ---------------------------------------------------------------------

    /**
     * @dev Blocks every transfer between two existing accounts.
     *
     * Minting (`from == address(0)`) and burning (`to == address(0)`) remain
     * permitted, which is what makes the token issuable and lets a holder
     * relinquish it. Everything else reverts.
     *
     * Enforced in `_update` rather than by overriding `transfer` and
     * `transferFrom`, because `_update` is the single funnel every balance
     * change passes through in OpenZeppelin v5. Overriding the public methods
     * would leave any future internal path unguarded; this cannot be bypassed.
     */
    function _update(address from, address to, uint256 value) internal override {
        if (from != address(0) && to != address(0)) {
            revert SoulboundTransferNotAllowed();
        }
        super._update(from, to, value);
    }

    /**
     * @dev Approvals are meaningless for a non-transferable token, so they are
     * refused rather than silently recorded. An allowance that can never be
     * spent is a promise the contract cannot keep, and integrators reading a
     * non-zero allowance would reasonably conclude a transfer is possible.
     */
    function approve(address, uint256) public pure override returns (bool) {
        revert SoulboundTransferNotAllowed();
    }

    /// @notice piQ is non-transferable. Always reverts.
    function transfer(address, uint256) public pure override returns (bool) {
        revert SoulboundTransferNotAllowed();
    }

    /// @notice piQ is non-transferable. Always reverts.
    function transferFrom(address, address, uint256) public pure override returns (bool) {
        revert SoulboundTransferNotAllowed();
    }

    // ---------------------------------------------------------------------
    // Minting
    // ---------------------------------------------------------------------

    /**
     * @notice Mint piQ against a Groth16 proof that the assessment met the
     *         circuit's quality threshold.
     * @param researcher       Recipient of the minted piQ.
     * @param amountWei        Amount in the token's smallest unit (18 decimals).
     * @param evalHash         Evaluation hash; used for replay protection.
     * @param truncatedHashInt Public input to the circuit.
     * @param proof            Groth16 proof produced by ZoKrates.
     */
    function verifyProofAndMint(
        address researcher,
        uint256 amountWei,
        string memory evalHash,
        uint256 truncatedHashInt,
        Verifier.Proof memory proof
    ) public onlyOwner {
        require(bytes(evalHash).length > 0, "Evaluation hash cannot be empty.");
        require(!hasBeenAssessed[evalHash], "Fraud detected: manuscript already assessed.");
        require(amountWei > 0, "Mint amount must be greater than zero.");
        require(researcher != address(0), "Cannot mint to the zero address.");

        uint256[1] memory publicInputs = [truncatedHashInt];
        require(
            zkVerifier.verifyTx(proof, publicInputs),
            "ZK-SNARK proof verification failed."
        );

        // Marked before minting: checks-effects-interactions, so even a future
        // change that makes _mint reentrant cannot replay this evaluation.
        hasBeenAssessed[evalHash] = true;
        _mint(researcher, amountWei);

        emit MintProofVerified(researcher, amountWei, evalHash);
    }

    /**
     * @notice Point the contract at a newly generated Verifier.
     * @dev The verifying key is baked into verifier.sol, so regenerating the
     *      circuit produces a new contract. Without this, a circuit change
     *      would strand the token and force a full redeployment, losing every
     *      minted balance.
     */
    function setVerifier(address _verifierAddress) external onlyOwner {
        require(_verifierAddress != address(0), "Verifier address cannot be zero");
        emit VerifierUpdated(address(zkVerifier), _verifierAddress);
        zkVerifier = Verifier(_verifierAddress);
    }

    // ---------------------------------------------------------------------
    // State registry
    // ---------------------------------------------------------------------

    /**
     * @notice Anchor the IPFS CID of the latest encrypted state backup.
     * @dev Owner-only. The CID points at ciphertext — the backup is encrypted
     *      before it leaves the server — so publishing it discloses that a
     *      backup exists and when, but not its contents.
     */
    function updateCID(string calldata cid) external onlyOwner {
        require(bytes(cid).length > 0, "CID cannot be empty.");
        _stateCID = cid;
        cidUpdatedAt = block.timestamp;
        emit StateCIDUpdated(cid, block.timestamp);
    }

    /// @notice The most recently anchored backup CID, or an empty string.
    function getCID() external view returns (string memory) {
        return _stateCID;
    }

    // ---------------------------------------------------------------------
    // Introspection
    // ---------------------------------------------------------------------

    /**
     * @notice Reports that this contract is live and correctly constructed.
     * @dev The application probes deployments before trusting them. The
     *      previous contract could not answer such a question — an
     *      uninitialized implementation returns empty strings and a zero owner
     *      while still being "deployed", which is indistinguishable from a
     *      healthy contract to anything that only checks for bytecode.
     */
    function isReady() external view returns (bool) {
        return owner() != address(0) && address(zkVerifier) != address(0);
    }
}
